// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ÖvningMinimalAPIOchEF.Data;

#nullable disable

namespace ÖvningMinimalAPIOchEF.Migrations
{
    [DbContext(typeof(CompanyAPIDbContext))]
    [Migration("20260115124515_SeedServicesAndCustomers")]
    partial class SeedServicesAndCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ÖvningMinimalAPIOchEF.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "katarina@gmail.com",
                            Name = "Katarina",
                            PhoneNr = "076-479 35 64"
                        },
                        new
                        {
                            Id = 2,
                            Email = "pelle@qlok.com",
                            Name = "Pelle",
                            PhoneNr = "070-756 49 61"
                        });
                });

            modelBuilder.Entity("ÖvningMinimalAPIOchEF.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Akut utryckning när kaffemaskinen strejkar. Inkluderar felsökning, pep talk och nödlösning med snabbkaffe.",
                            Name = "Kaffekrisjour",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vi förvandlar din röriga presentation till något som nästan ser proffsigt ut. Färger, ikoner och mindre Comic Sans.",
                            Name = "PowerPoint-räddning",
                            Price = 1299.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Personlig support där vi ställer exakt samma frågor som alla andra – men med bättre tonläge.",
                            Name = "IT-support",
                            Price = 299.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
